grpc:
  server:
    port: ${PIX_KEYMANAGER_APPLICATION_PORT:50051}

datasources:
  default:
    url: jdbc:h2:mem:keymanager_test_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""
    driverClassName: org.h2.Driver
hibernate:
  hbm2ddl:
    auto: update
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

