grpc:
  server:
    port: ${PIX_KEYMANAGER_APPLICATION_PORT:50051}

datasources:
  default:
    url: jdbc:postgresql://${PIX_KEYMANAGER_DEV_DATABASE_HOST:localhost}:${PIX_KEYMANAGER_DEV_DATABASE_PORT:5432}/${PIX_KEYMANAGER_DEV_DATABASE_NAME:pixkeymanager_dev_db}
    driverClassName: org.postgresql.Driver
    username: ${PIX_KEYMANAGER_DEV_DATABASE_USERNAME:postgres}
    password: ${PIX_KEYMANAGER_DEV_DATABASE_PASSWORD:postgres132}
    dialect: POSTGRES
    schema-generate: CREATE_DROP
hibernate:
  hbm2ddl:
    auto: update
jpa.default.properties.hibernate.hbm2ddl.auto: update

