micronaut:
  application:
    name: orangeTalents03TemplatePixKeymanagerGrpc

grpc:
  server:
    port: ${PIX_KEYMANAGER_APPLICATION_PORT:50051}

datasources:
  default:
    url: jdbc:h2:mem:pixkeymanager_test_db
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
jpa:
  default:
    properties:
      hibernate:
        bytecode:
          provider: none
        hbm2ddl:
          auto: update

itauErpService:
  url: http://localhost:9091/api/v1
  contas:
    path: /private/contas/todas
  cliente:
    path: /clientes/{id}
    contas:
      path: ${itauErpService.cliente.path}/contas

