micronaut:
  application:
    name: orangeTalents03TemplatePixKeymanagerGrpc

itauErpService:
  url: ${ITAUERP_URLasdas:`http://localhost:9091/api/v1`}
  contas:
    path: /private/contas/todas
  cliente:
    path: /clientes/{id}
    contas:
      path: ${itauErpService.cliente.path}/contas

bcbService:
  url: ${BCB_URL:`http://localhost:8082/api/v1`}
  keys:
    path: /pix/keys
    url: ${bcbService.url}${bcbService.keys.path}

